import torch
import torch.nn.functional as F
from torch.utils.data import Dataset

from src.predictors import Predictor
from src.utils import split_into_windows


class ARDataset(Dataset):
    """Autoregressive dataset generated by iteratively sampling from a Predictor.

    The predictor abstracts *what kind of teacher* generates the next token and
    *what type of sample* it produces (discrete one-hot vs continuous vector).
    The dataset itself is unaware of teacher classes, temperatures, or noise —
    those concerns live entirely in the predictor.

    Optional predictor hooks:
        random_burn_in(length) → Tensor: predictor-specific burn-in prefix
            (e.g. valid chunk-composed tokens for HierarchicalPredictor). Return
            None to use uniform-random one-hot fallback.
    """

    def __init__(
        self,
        predictor: Predictor,
        window: int,
        dim: int,
        number: int,
        length: int,
        prefix_length: int,
        unroll_sequences: bool = True,
    ) -> None:
        if prefix_length == -1:
            raise ValueError(
                "prefix_length must be provided (typically = teacher.context_length)."
            )
        self.predictor = predictor
        self.window = window
        self.dim = dim
        self.number = abs(number)
        self.length = length
        self.unroll_sequences = unroll_sequences
        self.refresh_sequences = number < 0
        self.prefix_length = prefix_length
        self.data = self._generate(self.number, self.length)

    def _burn_in(self, length: int) -> torch.Tensor:
        """Predictor-specific burn-in if available, else uniform one-hot fallback."""
        custom = self.predictor.random_burn_in(length)
        if custom is not None:
            return custom
        indices = torch.randint(0, self.dim, (length,))
        return F.one_hot(indices, num_classes=self.dim).float()

    def _generate_seq(self, length: int) -> torch.Tensor:
        seq = torch.zeros((self.prefix_length + length, self.dim))
        seq[: self.prefix_length, :] = self._burn_in(self.prefix_length)
        for i in range(self.prefix_length, seq.shape[0]):
            seq[i, :] = self.predictor.sample_next(seq[:i, :])
        return seq

    def _generate(self, number: int, length: int) -> torch.Tensor:
        return torch.stack([self._generate_seq(length) for _ in range(number)])

    def __len__(self) -> int:
        return self.number

    def __getitem__(self, index: int) -> torch.Tensor:
        if self.refresh_sequences:
            self.data[index : index + 1, ...] = self._generate(1, self.length)

        if self.unroll_sequences:
            return split_into_windows(
                torch.unsqueeze(self.data[index, ...], dim=0), self.window
            )
        return self.data[index, ...]
