from typing import List

import torch
import torch.nn.functional as F
import tqdm
from torch.utils.data import Dataset

from src.predictors import Predictor
from src.profiling import get_profiler
from src.utils import split_into_windows


def ar_batch_collate(batch: torch.Tensor) -> torch.Tensor:
    """Passthrough collate: ARDataset.__getitems__ already returns a stacked
    (B, T, D) tensor. Default collate would iterate the tensor row-by-row and
    re-stack — wasted memcpy at large B."""
    return batch


class ARDataset(Dataset):
    """Autoregressive dataset generated by iteratively sampling from a Predictor.

    The predictor abstracts *what kind of teacher* generates the next token and
    *what type of sample* it produces (discrete one-hot vs continuous vector).
    The dataset itself is unaware of teacher classes, temperatures, or noise —
    those concerns live entirely in the predictor.

    Optional predictor hooks:
        random_burn_in(length) → Tensor: predictor-specific burn-in prefix
            (e.g. valid chunk-composed tokens for HierarchicalPredictor). Return
            None to use uniform-random one-hot fallback.
    """

    def __init__(
        self,
        predictor: Predictor,
        window: int,
        dim: int,
        number: int,
        length: int,
        prefix_length: int,
        unroll_sequences: bool = True,
    ) -> None:
        if prefix_length == -1:
            raise ValueError(
                "prefix_length must be provided (typically = teacher.context_length)."
            )
        self.predictor = predictor
        self.window = window
        self.dim = dim
        self.number = abs(number)
        self.length = length
        self.unroll_sequences = unroll_sequences
        self.refresh_sequences = number < 0
        self.prefix_length = prefix_length
        if self.refresh_sequences:
            # Pure lazy: no cache — every fetch regenerates.
            self.data = None
        else:
            with get_profiler().cuda("dataset_init"):
                self.data = self._generate(self.number, self.length)

    def _burn_in(self, length: int) -> torch.Tensor:
        """Predictor-specific burn-in if available, else uniform one-hot fallback."""
        custom = self.predictor.random_burn_in(length)
        if custom is not None:
            return custom
        indices = torch.randint(0, self.dim, (length,))
        return F.one_hot(indices, num_classes=self.dim).float()

    def _burn_in_batch(self, batch_size: int, length: int) -> torch.Tensor:
        """Batched predictor-specific burn-in, else uniform one-hot fallback."""
        custom = self.predictor.random_burn_in_batch(batch_size, length)
        if custom is not None:
            return custom
        indices = torch.randint(0, self.dim, (batch_size, length))
        return F.one_hot(indices, num_classes=self.dim).float()

    def _generate_seq(self, length: int) -> torch.Tensor:
        seq = torch.zeros((self.prefix_length + length, self.dim))
        seq[: self.prefix_length, :] = self._burn_in(self.prefix_length)
        for i in range(self.prefix_length, seq.shape[0]):
            seq[i, :] = self.predictor.sample_next(seq[:i, :])
        return seq

    def _generate(self, number: int, length: int) -> torch.Tensor:
        """Batched dataset generation: one teacher forward per position across
        all `number` sequences simultaneously, instead of `number` independent
        Python loops.
        """
        total_len = self.prefix_length + length
        seq = torch.zeros((number, total_len, self.dim))
        seq[:, : self.prefix_length, :] = self._burn_in_batch(number, self.prefix_length)
        pbar = tqdm.trange(
            self.prefix_length,
            total_len,
            desc=f"Generating {number}x len={total_len}",
            leave=False,
            unit="pos",
            disable=number < 4,
        )
        for i in pbar:
            seq[:, i, :] = self.predictor.sample_next_batch(seq[:, :i, :])
        return seq

    def __len__(self) -> int:
        return self.number

    def __getitem__(self, index: int) -> torch.Tensor:
        if self.refresh_sequences:
            with get_profiler().cuda("sample_batch"):
                seq = self._generate(1, self.length)[0]
        else:
            seq = self.data[index]

        if self.unroll_sequences:
            return split_into_windows(torch.unsqueeze(seq, dim=0), self.window)
        return seq

    def __getitems__(self, indices: List[int]) -> torch.Tensor:
        """Batched fetch (PyTorch DataLoader hook, ≥1.11).

        In refresh mode this replaces `len(indices)` independent per-token
        teacher forwards with one batched forward per position — the same
        speedup as init-time batched generation. Must be paired with a
        passthrough `collate_fn` (see `ar_batch_collate`) so the returned
        (B, T, D) tensor isn't torn apart and re-stacked by default collate.
        """
        if self.refresh_sequences:
            with get_profiler().cuda("sample_batch"):
                batch = self._generate(len(indices), self.length)
        else:
            batch = self.data[indices]

        if self.unroll_sequences:
            return split_into_windows(batch, self.window)
        return batch
